services:
  - type: web
    name: news-aggregator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: news-db
          property: connectionString
      - key: RSS_FEEDS
        value: "https://rss.cnn.com/rss/edition.rss,https://feeds.bbci.co.uk/news/rss.xml,https://www.reuters.com/rssFeed/topNews"
      - key: CRON_SECRET
        generateValue: true

  - type: pserv
    name: news-db
    env: postgresql
    plan: free